### PR TITLE
Refactored code to allow packaging on PyPi. Fixes #1

### LINKED ISSUE #1: PyPi Release

### PR DESCRIPTION
**Pull request by vascowhite**
- Moved down.py to `down/down.py`
- Created setup.py
- Created `down/__init__.py`
- Created `down/__main__.py`
- Created `down/__version__.py`
- Removed requirements.txt as depes are now in setup.py
- Modified README.md to reflect new installation method and useage

Package now installs with a directly useable comand.
i.e. Just type `down urltotest.com`, rather than `python3 down urltotest.com`

---

Siddarth, to deploy this you will need to create an account on [Pypi](https://pypi.org/).
To deploy you will need to install twine. `pip install twine`

After that you should cd into the top `down` directory and issue the following commands:-

```bash
$ python3 setup.py  sdist bdist-wheel
$ twine upload dist/*
```

You will be asked for your username and password for PyPi and voila! You have distributed a package.

Test everything locally before uploading though.

### CODE REVIEW

**Comment by vascowhite** [comment]
Sorry it took so long, busy at work.
Take a look and see what you think. Feel free to ask questions.

**Comment by sdushantha** [comment]
Thank you Paul for doing this! 
I will read through the code and test everything locally before uploading. At the moment, I am a bit busy so will upload this to PyPi and merge this next week. 
Hope that ok with you. :)

**Comment by vascowhite** [comment]
I see there is already a package called [down](https://pypi.org/project/down/), so you will need to change the name.

I also found [another package](https://pypi.org/project/website-up/) similar to yours, but I think yours is coded better.

**Comment by sdushantha** [comment]
I guess I could name the package pydown but the the command line app can be called down.

---
So when installing it:

```bash
pip install pydown
```

And when using it:
```bash
down https://www.example.com
```
---

Would that work?


EDIT: Never mind, there is also a package called [pydown](https://pypi.org/project/pydown/)

**Comment by vascowhite** [comment]
Yes, but I think I'll need to change the code slightly.
Let me do some testing here and I'll get back to you in the next few
days.

**Comment by sdushantha** [comment]
Ok thanks

**Pull request closed without merging**
